version: "3.8"

services:
  pizza_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: pizza_framework
    working_dir: /var/www/html
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - mysql
    networks:
      - pizza

  mysql:
    image: mysql:8.0-oracle
    container_name: pizza_mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - pizza

networks:
  pizza:
    driver: bridge
